// Generated by Wrangler by running `wrangler types`
// WARNING: `wrangler types` will overwrite this file. If you add custom
// bindings (like CONTACT_EMAIL), re-add them after regenerating.

interface Env {
	ASSETS: Fetcher;
	PRODUCT_CACHE: KVNamespace;
	STRIPE_SECRET_KEY: string;
	STRIPE_WEBHOOK_SECRET: string;
	CONTACT_EMAIL: SendEmail;
}
