// Generated by Wrangler by running `wrangler types`

interface Env {
	ASSETS: Fetcher;
	PRODUCT_CACHE: KVNamespace;
	STRIPE_SECRET_KEY: string;
	STRIPE_WEBHOOK_SECRET: string;
	CONTACT_EMAIL: SendEmail;
}
