/**
 * Repo-managed catalog for Stripe products.
 * Generated from current Stripe products.
 */

export default [
  {
    key: "avatar-the-last-airbender-jumpstart-booster-display-avatar-the-last-airbender-tla",
    name: "Avatar: The Last Airbender - Jumpstart Booster Display - Avatar: The Last Airbender (TLA)",
    description: "Hold on to your cabbages—the mash-up mayhem is about to begin. Grab two boosters, shuffle them together, and you're ready to go! ",
    category: "magic",
    price: 11246,
    image: "https://files.stripe.com/links/MDB8YWNjdF8xU2JEWWRSM1djdWNhUXFwfGZsX2xpdmVfMk5xd2xjVTRjdGh0dnVEV010dUNYWHFj00pdTT6PgU",
    sortOrder: 999,
    active: true,
    quantity: 3,
  },
  {
    key: "avatar-the-last-airbender-play-booster-display-avatar-the-last-airbender-tla",
    name: "Avatar: The Last Airbender - Play Booster Display - Avatar: The Last Airbender (TLA)",
    description: "Team Avatar is back! The action, adventure, and spirit of Avatar: The Last Airbender awaken in Magic: The Gathering. Relive the series with iconic scenes, collect cards featuring your favorite characters, and master Avatar: The Last Airbender-themed game mechanics. The balance and harmony of the four nations is in your hands.",
    category: "magic",
    price: 13823,
    image: "https://files.stripe.com/links/MDB8YWNjdF8xU2JEWWRSM1djdWNhUXFwfGZsX2xpdmVfSkFldEJxZGJkZmhLOXRKcUh5NFBmdUtK00D01JqF69",
    sortOrder: 999,
    active: true,
    quantity: 4,
  },
  {
    key: "final-fantasy-play-booster-display-final-fantasy-fin",
    name: "FINAL FANTASY - Play Booster Display - FINAL FANTASY (FIN)",
    description: "The entire FINAL FANTASY saga is here! Your players will step into the worlds of the beloved FINAL FANTASY RPG series' sixteen mainline games. ",
    category: "magic",
    price: 14645,
    image: "https://files.stripe.com/links/MDB8YWNjdF8xU2JEWWRSM1djdWNhUXFwfGZsX2xpdmVfQXJHdEZ5c2JvODJYaU1oWU1ySFRCUkpY00Yk8eOzGR",
    sortOrder: 999,
    active: true,
    quantity: 1,
  },
  {
    key: "innistrad-crimson-vow-collector-booster-display-innistrad-crimson-vow-vow",
    name: "Innistrad: Crimson Vow - Collector Booster Display - Innistrad: Crimson Vow (VOW)",
    description: "• 12 Innistrad: Crimson Vow MTG Collector Boosters• 2 sealed box topper cards• 15 Magic cards + 1 foil token in each booster• Loaded with rares, foils, special treatments, and more• 5 Rare and/or Mythic Rare cards per pack• Return to the gothic horror plane of Innistrad for a sumptuous vampire wedding—as honored guest or delicious entrée",
    category: "magic",
    price: 24217,
    image: "https://files.stripe.com/links/MDB8YWNjdF8xU2JEWWRSM1djdWNhUXFwfGZsX2xpdmVfUUlSeVZkaEtMc1Y1dFNRRDQyTVB3dnc50052x3U7a5",
    sortOrder: 999,
    active: true,
    quantity: 1,
  },
  {
    key: "kamigawa-neon-dynasty-collector-booster-display-kamigawa-neon-dynasty-neo",
    name: "Kamigawa: Neon Dynasty - Collector Booster Display - Kamigawa: Neon Dynasty (NEO)",
    description: "The Kamigawa: Neon Dynasty Collector Booster Box contains 12 Kamigawa: Neon Dynasty Collector Boosters. Each Collector Booster contains 15 Magic: The Gathering cards and 1 traditional foil double-sided token, with a combination of 5 cards of rarity Rare or higher, 2–7 Uncommons, 2–7 Common cards, and 1 Land card.",
    category: "magic",
    price: 43319,
    image: "https://files.stripe.com/links/MDB8YWNjdF8xU2JEWWRSM1djdWNhUXFwfGZsX2xpdmVfVkdRZGhGNEU5NXRVR2ZocnZvZGNXVnZT007u2d3DEO",
    sortOrder: 999,
    active: true,
    quantity: 1,
  },
  {
    key: "lorwyn-eclipsed-collector-booster-display-lorwyn-eclipsed-ecl",
    name: "Lorwyn Eclipsed - Collector Booster Display - Lorwyn Eclipsed (ECL)",
    description: "Gather a bountiful bouquet of the brightest and boldest from Lorwyn Eclipsed! Each booster pack contains rares and/or mythic rares, foils, and a full-art basic land in either its Lorwyn or Shadowmoor form. You may also happen upon borderless reversible shock lands, fable frame cards, and borderless cards illustrated by classic Magic artists.",
    category: "magic",
    price: 39999,
    image: "https://files.stripe.com/links/MDB8YWNjdF8xU2JEWWRSM1djdWNhUXFwfGZsX2xpdmVfbUNUQ25QNHRMdnpmYnNpWThaaWx6Slcx00ndTyxemn",
    sortOrder: 999,
    active: true,
    quantity: 3,
  },
  {
    key: "lorwyn-eclipsed-play-booster-display-lorwyn-eclipsed-ecl",
    name: "Lorwyn Eclipsed - Play Booster Display - Lorwyn Eclipsed (ECL)",
    description: "Dare to enter the ever-changing plane of Lorwyn and Shadowmoor. Summon beloved Kithkin, boggarts, merrow, and Elves, that feature new and returning mechanics as well as art from new and returning Lorwyn™ artists! Discover your true self by crossing the boundary of eternal day into eternal night and rising triumphant as a master of order and chaos.",
    category: "magic",
    price: 13512,
    image: "https://files.stripe.com/links/MDB8YWNjdF8xU2JEWW9KY3hBbmtYWm16fGZsX3Rlc3RfYXA1M2VBcm5RTm8wNmk3dllWM0w5dEFY00mh9H6kBG",
    sortOrder: 999,
    active: true,
    quantity: 10,
  },
  {
    key: "magic-the-gathering-foundations-play-booster-display-foundations-fdn",
    name: "Magic: The Gathering Foundations - Play Booster Display - Foundations (FDN)",
    description: "The best time for your community's first Magic game is now. Dive into Foundations, and experience quintessential Magic: The Gathering by playing with and collecting cards selected to give every player the advantage. Whether a past, present, or future Magic player, Foundations invite you to share your spark!Play Boosters are the best way to discover all that Magic has to offer.",
    category: "magic",
    price: 14022,
    image: "https://files.stripe.com/links/MDB8YWNjdF8xU2JEWWRSM1djdWNhUXFwfGZsX2xpdmVfcDQ1RGpabnF2VUpxSWJ6VmhBZEl4Q21H00sMXib3xm",
    sortOrder: 999,
    active: true,
    quantity: 2,
  },
  {
    key: "marvel-s-spider-man-collector-booster-display",
    name: "Marvel's Spider-Man - Collector Booster Display",
    description: "Your friendly neighborhood Spider-Man swings into Magic: The Gathering, and not a moment too soon! Gather web-slingers from across the Spider-Verse and team up to take down the sinister foes that threaten the city. Keep your Spider-Senses primed to spot Borderless treatments that leap right off the page!",
    category: "magic",
    price: 56674,
    image: "https://files.stripe.com/links/MDB8YWNjdF8xU2JEWWRSM1djdWNhUXFwfGZsX2xpdmVfTmN6RXVlZVNlcEFHcHFFZHpkWDB6NHB400AIlKZ4E4",
    sortOrder: 999,
    active: true,
    quantity: 1,
  },
  {
    key: "marvel-s-spider-man-play-booster-display-marvel-s-spider-man-spm",
    name: "Marvel's Spider-Man - Play Booster Display - Marvel's Spider-Man (SPM)",
    description: "Your friendly neighborhood Spider-Man swings into Magic: The Gathering, and not a moment too soon! Gather web-slingers from across the Spider-Verse and team up to take down the sinister foes that threaten the city. Keep your Spider-Senses primed to spot Borderless treatments that leap right off the page!Play Boosters are the best way to discover all that Magic has to offer. ",
    category: "magic",
    price: 12107,
    image: "https://files.stripe.com/links/MDB8YWNjdF8xU2JEWWRSM1djdWNhUXFwfGZsX2xpdmVfbUhzSmdqdDBsTmRBdVFsb0NrY0tZcXJP00IlgOz1BL",
    sortOrder: 999,
    active: true,
    quantity: 1,
  },
  {
    key: "secrets-of-strixhaven-play-booster-display-secrets-of-strixhaven-sos",
    name: "Secrets of Strixhaven - Play Booster Display - Secrets of Strixhaven (SOS)",
    description: "Return to Strixhaven, Magic's beloved mage school, and uncover years of mysteries as you explore its hallowed halls and beyond. The five colleges are back, each with their own unique look, feel, and magic focus. As you increase your skills, make academic discoveries and work to prove your college is the best, but beware—second-year knowledge comes with a side of increased danger.",
    category: "magic",
    price: 13002,
    image: "https://files.stripe.com/links/MDB8YWNjdF8xU2JEWWRSM1djdWNhUXFwfGZsX2xpdmVfdFk4b05jTFBIU1o0ZGtuRFc1RkRycGVa00lWautCp1",
    sortOrder: 999,
    active: true,
    quantity: 2,
  },
  {
    key: "tarkir-dragonstorm-play-booster-display-tarkir-dragonstorm-tdm",
    name: "Tarkir: Dragonstorm - Play Booster Display - Tarkir: Dragonstorm (TDM)",
    description: "Return to the iconic plane of Tarkir for an epic battle between dragons and clans. As powerful dragonstorms spiral Tarkir into chaos and wild dragons darken the skies, the five clans fight alongside their new Spirit Dragons for supremacy over the land. Discover which clan fits your playstyle with Tarkir's distinct three-color gameplay.",
    category: "magic",
    price: 13017,
    image: "https://files.stripe.com/links/MDB8YWNjdF8xU2JEWWRSM1djdWNhUXFwfGZsX2xpdmVfdlYzeFFQYldJNDRxWVpwdm01QmJuYWdq00ZRVVZQMI",
    sortOrder: 999,
    active: true,
    quantity: 2,
  },
  {
    key: "teenage-mutant-ninja-turtles-play-booster-display-teenage-mutant-ninja-turtles-tmt",
    name: "Teenage Mutant Ninja Turtles - Play Booster Display - Teenage Mutant Ninja Turtles (TMT)",
    description: "Tap into Turtle power!Magic: The Gathering gets a quadruple dose of mutagenic mayhem as the Teenage Mutant Ninja Turtles make their debut on the battlefield! Collect, construct, and combat with an iconic roster of allies and enemies from four decades of time-tested Turtle-mania. Get the drop on Shredder's goons with the all-new sneak mechanic, then enhance your team's strength with Mutagen tokens to rise triumphant like the true heroes of New York!",
    category: "magic",
    price: 13946,
    image: "https://files.stripe.com/links/MDB8YWNjdF8xU2JEWWRSM1djdWNhUXFwfGZsX2xpdmVfTFhFUmtnQjI2QTBVN0N1MVN3S3VQRWY300SPJS5HYi",
    sortOrder: 999,
    active: true,
    quantity: 6,
  },
  {
    key: "wilds-of-eldraine-collector-booster-display-wilds-of-eldraine-woe",
    name: "Wilds of Eldraine - Collector Booster Display - Wilds of Eldraine (WOE)",
    description: "Eldraine is a plane of wonderful chaos and contradictions—your players will be invited to start their own storybook adventure, enveloped in a fantastical fairytale with a twist to break the curse of an endless slumber.With Collector Boosters, your players get direct access to the coolest cards from the set. A full display of Collector Boosters helps players strategize in style.",
    category: "magic",
    price: 113316,
    image: "https://files.stripe.com/links/MDB8YWNjdF8xU2JEWWRSM1djdWNhUXFwfGZsX2xpdmVfbFJxdHAyNmJpTnZSeU1MSUx5dlpHcDE5008Sc7iDAu",
    sortOrder: 999,
    active: true,
    quantity: 1,
  },
];
