/**
 * Repo-managed catalog for Stripe products.
 * Generated from current Stripe products.
 */

export default [
  {
    key: "avatar-the-last-airbender-jumpstart-booster-display-avatar-the-last-airbender-tla",
    name: "Avatar: The Last Airbender - Jumpstart Booster Display - Avatar: The Last Airbender (TLA)",
    description: "Avatar: The Last Airbender Jumpstart Booster Display contains 24 ready-to-play boosters, each packed with 20 Magic: The Gathering cards built around one of 46 distinct themes inspired by the animated series. Pick two packs, shuffle them together, and you're in for a duel—no deck building required.\n\nThemes draw from across all four nations: Fire Nation aggression, Water Tribe control, Earth Kingdom resilience, and Air Nomad finesse. You'll find legendary creatures based on Aang, Katara, Sokka, Toph, and Zuko, alongside iconic locations and artifacts from the show rendered in Magic card form. Every Jumpstart booster includes an exclusive full-art Appa land card, a collector's staple that won't appear in any other Avatar product.\n\nWith 46 different deck themes spread across 24 packs, each display offers a wide variety of play experiences straight out of the box. Whether you're running a casual game night for Avatar fans, shopping for a birthday gift for a Magic player who loves the show, or hunting the full-art Appa for your collection, this Jumpstart display delivers immediate, thematic fun with zero setup friction.\n\nFactory sealed and sourced from authorized Wizards of the Coast distributors. Ships within the United States via USPS.",
    category: "magic",
    price: 11246,
    image: "https://files.stripe.com/links/MDB8YWNjdF8xU2JEWWRSM1djdWNhUXFwfGZsX2xpdmVfMk5xd2xjVTRjdGh0dnVEV010dUNYWHFj00pdTT6PgU",
    sortOrder: 999,
    active: true,
    quantity: 3,
  },
  {
    key: "avatar-the-last-airbender-play-booster-display-avatar-the-last-airbender-tla",
    name: "Avatar: The Last Airbender - Play Booster Display - Avatar: The Last Airbender (TLA)",
    description: "Avatar: The Last Airbender comes to Magic: The Gathering in one of Universes Beyond's most anticipated crossovers. This Play Booster Display contains 30 packs, each with 14 cards and a guaranteed rare or better alongside at least one traditional foil. With 420 cards across the box, you'll have everything you need to draft, build Standard-legal decks, or chase the set's most coveted collectibles.\n\nThe set features legendary versions of the series' core cast—Avatar Aang, Katara, Sokka, Toph, Zuko, and Azula—as well as iconic villains, allies, and locations from the show. Elemental bending translates into keyword mechanics: expect cards that reward air, water, earth, and fire-themed strategies that mirror each nation's combat style. Spirit creatures, bending showcase cards, and full-art lands themed around the four nations add serious collector pull.\n\nChase targets include Borderless Anime showcase cards featuring the main cast in art that looks pulled straight from the original Nickelodeon series, as well as foil treatments across the rarity spectrum. The set is legal in Standard and Commander formats.\n\nIdeal for draft nights, sealed events, or collecting the full Avatar roster in Magic card form. Factory sealed, sourced from authorized Wizards of the Coast distributors, and shipped within the United States via USPS.",
    category: "magic",
    price: 13823,
    image: "https://files.stripe.com/links/MDB8YWNjdF8xU2JEWWRSM1djdWNhUXFwfGZsX2xpdmVfSkFldEJxZGJkZmhLOXRKcUh5NFBmdUtK00D01JqF69",
    sortOrder: 999,
    active: true,
    quantity: 4,
  },
  {
    key: "final-fantasy-play-booster-display-final-fantasy-fin",
    name: "FINAL FANTASY - Play Booster Display - FINAL FANTASY (FIN)",
    description: "Sixteen worlds. Countless heroes and villains. One booster display. The FINAL FANTASY Play Booster Display brings the complete mainline FINAL FANTASY saga—from FF1 through FF16—to Magic: The Gathering in a single, sprawling Universes Beyond set.\n\nThis display contains 30 Play Boosters, each with 14 cards and at least one traditional foil. With cards spanning over three decades of FINAL FANTASY history, collectors and fans will find iconic summons like Bahamut, Shiva, and Ifrit alongside legendary characters including Cloud, Lightning, Terra, Tidus, and Vivi. The set's mechanical identity leans into RPG progression and party-building themes, giving players multiple angles to build Commander and Standard decks.\n\nSignature showcase treatments include iconic in-game artwork frames, job-class card borders, and special foil-stamped art cards. Art cards appear in 30% of packs and foil-stamped signature art cards in 5%, making each pack worth examining closely. Traditional foil treatments show up across all rarities.\n\nWhether you're a lifelong FINAL FANTASY fan discovering Magic for the first time, an MTG player building a Crystal Chronicles Commander deck, or a collector hunting the Black Mage or Warrior of Light in cardboard form, this display is the complete box to crack.\n\nFactory sealed, sourced from authorized Wizards of the Coast distributors. Ships within the United States via USPS.",
    category: "magic",
    price: 14645,
    image: "https://files.stripe.com/links/MDB8YWNjdF8xU2JEWWRSM1djdWNhUXFwfGZsX2xpdmVfQXJHdEZ5c2JvODJYaU1oWU1ySFRCUkpY00Yk8eOzGR",
    sortOrder: 999,
    active: true,
    quantity: 1,
  },
  {
    key: "innistrad-crimson-vow-collector-booster-display-innistrad-crimson-vow-vow",
    name: "Innistrad: Crimson Vow - Collector Booster Display - Innistrad: Crimson Vow (VOW)",
    description: "Innistrad: Crimson Vow Collector Booster Display is the premium product for fans of Magic's gothic horror plane. This display contains 12 Collector Boosters plus 2 sealed box topper cards—rare extended-art versions of some of Crimson Vow's most powerful spells delivered outside the packs as an exclusive bonus.\n\nEach Collector Booster holds 15 Magic cards and 1 traditional foil token, with 5 guaranteed rares or mythic rares per pack. Premium contents include extended-art cards, borderless alternate-art versions of the set's most powerful spells, and etched foil treatments on fan-favorite legends. Phyrexian language showcase cards, Fang-frame treatments, and Stained Glass lands round out the collector content that makes Crimson Vow worth opening long after release.\n\nThe story follows Sorin Markov orchestrating a forced wedding between rival vampire bloodlines on a moonlit Innistrad—and the Collector Booster treatment brings the set's most dramatic moments to life with art and frame treatments you won't find in standard packs. Key Commander staples and eternal format playables appear throughout the set, giving this display strong long-term value beyond the initial crack.\n\nAn excellent box for Commander players building tribal vampire decks or collectors chasing the full Crimson Vow showcase cycle. Factory sealed, sourced from authorized Wizards of the Coast distributors. Ships within the United States via USPS.",
    category: "magic",
    price: 24217,
    image: "https://files.stripe.com/links/MDB8YWNjdF8xU2JEWWRSM1djdWNhUXFwfGZsX2xpdmVfUUlSeVZkaEtMc1Y1dFNRRDQyTVB3dnc50052x3U7a5",
    sortOrder: 999,
    active: true,
    quantity: 1,
  },
  {
    key: "kamigawa-neon-dynasty-collector-booster-display-kamigawa-neon-dynasty-neo",
    name: "Kamigawa: Neon Dynasty - Collector Booster Display - Kamigawa: Neon Dynasty (NEO)",
    description: "Kamigawa: Neon Dynasty reimagined Magic's feudal Japan-inspired plane through a cyberpunk lens—neon cities, technological ninja, and ancient spirits coexist in one of Magic's most visually distinctive sets. This Collector Booster Display contains 12 Kamigawa: Neon Dynasty Collector Boosters, the fastest route to the set's most spectacular cards.\n\nEach Collector Booster holds 15 Magic cards and 1 traditional foil double-sided token, with 5 rares or mythic rares guaranteed per pack. You'll find extended-art treatments, Neon Ink showcase cards featuring the set's legendary creatures in a bold retro-futuristic art style, and borderless alternate-art planeswalkers. Foil-etched showcase cards and Saga frame treatments make Neon Dynasty Collector Boosters some of the most visually striking in Magic history.\n\nNeon Dynasty is home to several Commander format powerhouses and eternal-legal staples that have maintained significant value since release. The set introduced the Channel and Reconfigure mechanics—both of which have seen continued play in competitive formats—and the legendary creature count is among the highest of any Magic set, feeding Commander deck building for years.\n\nWith strong foil density, desirable reprints, and an aesthetic unlike any other Magic set, this Collector Booster Display is an excellent pickup for collectors, Commander players, and fans of Japanese pop culture alike. Factory sealed, sourced from authorized Wizards of the Coast distributors. Ships within the United States via USPS.",
    category: "magic",
    price: 43319,
    image: "https://files.stripe.com/links/MDB8YWNjdF8xU2JEWWRSM1djdWNhUXFwfGZsX2xpdmVfVkdRZGhGNEU5NXRVR2ZocnZvZGNXVnZT007u2d3DEO",
    sortOrder: 999,
    active: true,
    quantity: 1,
  },
  {
    key: "lorwyn-eclipsed-collector-booster-display-lorwyn-eclipsed-ecl",
    name: "Lorwyn Eclipsed - Collector Booster Display - Lorwyn Eclipsed (ECL)",
    description: "Lorwyn Eclipsed Collector Booster Display is the premium configuration for one of 2025's most collector-focused Magic releases. This display contains 12 Collector Boosters, each loaded with 15 Magic cards—11 to 12 of which are traditional foils—with 5 guaranteed rares or mythic rares per pack. Every booster includes a full-art basic land in either its Lorwyn daytime form or its Shadowmoor twilight variant.\n\nThe set merges two beloved worlds—the sun-drenched Lorwyn and its dark mirror, Shadowmoor—into a single plane that shifts between eternal day and endless night. Collector Boosters are where the most spectacular treatments live: borderless reversible Shock Lands, Fable-frame cards depicting the plane's most legendary moments, and borderless cards illustrated by artists who defined the original Lorwyn and Shadowmoor sets in 2007.\n\nThe headliner chase is 1-of-500 serialized cards featuring Rebecca Guay art—some of Magic's most iconic and collectible illustrations. The Shock Land cycle drives serious long-term collector value, as these eternal and Commander staples are among the most played non-basic lands in Magic history.\n\nWhether you're hunting Guay's iconic art cards, chasing the foil Shock Land cycle, or building a tribal creature Commander deck, the Lorwyn Eclipsed Collector Display delivers exceptional value. Factory sealed, sourced from authorized Wizards of the Coast distributors. Ships within the United States via USPS.",
    category: "magic",
    price: 39999,
    image: "https://files.stripe.com/links/MDB8YWNjdF8xU2JEWWRSM1djdWNhUXFwfGZsX2xpdmVfbUNUQ25QNHRMdnpmYnNpWThaaWx6Slcx00ndTyxemn",
    sortOrder: 999,
    active: true,
    quantity: 3,
  },
  {
    key: "lorwyn-eclipsed-play-booster-display-lorwyn-eclipsed-ecl",
    name: "Lorwyn Eclipsed - Play Booster Display - Lorwyn Eclipsed (ECL)",
    description: "Lorwyn Eclipsed Play Booster Display contains 30 Play Boosters, each with 14 Magic: The Gathering cards, a guaranteed rare or better, and at least one traditional foil. The display offers 420 total cards spread across the merged Lorwyn and Shadowmoor planes—a crossroads of eternal day and endless twilight where creature tribes battle for the soul of the plane.\n\nKithkin, boggarts, merrow, Elves, Faeries, Giants, and Treefolk return from the original 2007 Lorwyn block, now joined by Shadowmoor's corrupted counterparts and the eerie creatures that thrive in the darkness between. New and returning mechanics capture the plane's dual nature: tribal synergies dominate the early turns while Shadowmoor's harsh countermeasures punish overextension.\n\nCollectors will want to chase Borderless showcase treatments, alternate-art legendary creatures drawn by artists who worked on the original sets, and the foil Shock Land cycle that appears across both Play and Collector product. The set is legal in Standard and Commander formats, and the tribal-focused card pool feeds existing Commander decks centered around Faeries, Elves, Merfolk, and Treefolk.\n\nAt an accessible price point for a 30-pack display, Lorwyn Eclipsed is an ideal box for draft nights, casual sealed events, or building out format-legal creature tribal decks. Factory sealed, sourced from authorized Wizards of the Coast distributors. Ships within the United States via USPS.",
    category: "magic",
    price: 13512,
    image: "https://files.stripe.com/links/MDB8YWNjdF8xU2JEWW9KY3hBbmtYWm16fGZsX3Rlc3RfYXA1M2VBcm5RTm8wNmk3dllWM0w5dEFY00mh9H6kBG",
    sortOrder: 999,
    active: true,
    quantity: 10,
  },
  {
    key: "magic-the-gathering-foundations-play-booster-display-foundations-fdn",
    name: "Magic: The Gathering Foundations - Play Booster Display - Foundations (FDN)",
    description: "Magic: The Gathering Foundations Play Booster Display is the essential set for new and returning players—and a reprint treasure for veterans. Designed as a milestone release, Foundations curates the most iconic, accessible, and useful cards from across Magic's 30+ year history into a single set that's legal in Standard and every major format.\n\nEach Play Booster contains 14 Magic cards with a guaranteed rare or better, a traditional foil, and a mix of commons, uncommons, and lands. The set's card list targets gameplay fundamentals: clean, powerful effects with minimal complexity that teach core Magic concepts while remaining competitive enough for experienced players. For Commander players, the set offers widely-played staples in fresh art, often at more accessible prices than previous printings.\n\nFor new players cracking their first booster box, Foundations provides the most well-rounded starting collection in years. For returning players, it's a direct reprint of cards they remember from earlier formats in a fresh Standard-legal shell. Every rare slot carries genuine utility across multiple formats, keeping pack-opening satisfying regardless of what you pull.\n\nThis display makes an ideal gift for someone getting into Magic, a store's tournament prize support box, or a household collection starter. Factory sealed, sourced from authorized Wizards of the Coast distributors. Ships within the United States via USPS.",
    category: "magic",
    price: 14022,
    image: "https://files.stripe.com/links/MDB8YWNjdF8xU2JEWWRSM1djdWNhUXFwfGZsX2xpdmVfcDQ1RGpabnF2VUpxSWJ6VmhBZEl4Q21H00sMXib3xm",
    sortOrder: 999,
    active: true,
    quantity: 2,
  },
  {
    key: "marvel-s-spider-man-collector-booster-display",
    name: "Marvel's Spider-Man - Collector Booster Display",
    description: "Marvel's Spider-Man Collector Booster Display brings 12 premium packs of the wall-crawler's Magic: The Gathering debut. Each Collector Booster delivers 15 cards with maximum foil density—including 5 guaranteed rares or mythic rares per pack—making this the fastest way to pull the set's most coveted Borderless and alternate-art treatments.\n\nThe Spider-Man set swings across the Spider-Verse, bringing Peter Parker, Miles Morales, Ghost-Spider, Silk, Spider-Man 2099, and the full rogues' gallery into cardboard form. Collector Boosters are where the Borderless comic-art showcase cards live: illustrations designed to look like panels pulled directly from Marvel comics, complete with the bold linework and color palette fans know from four decades of Spider-Man stories.\n\nChase targets include Borderless showcase cards for each major Spider-hero and villain, traditional foil mythic rares, and serialized premium versions of top-tier legendary creatures. The set introduces web counter mechanics that reward building around Spider-team synergies, giving Commander players a strong tribal shell with immediate competitive potential.\n\nThis display is the right product for Marvel collectors, Spider-Man fans, and Commander players who want every premium treatment in one box. A full Collector Display maximizes your odds on the set's most spectacular borderless art cards.\n\nFactory sealed, sourced from authorized Wizards of the Coast distributors. Ships within the United States via USPS.",
    category: "magic",
    price: 56674,
    image: "https://files.stripe.com/links/MDB8YWNjdF8xU2JEWWRSM1djdWNhUXFwfGZsX2xpdmVfTmN6RXVlZVNlcEFHcHFFZHpkWDB6NHB400AIlKZ4E4",
    sortOrder: 999,
    active: true,
    quantity: 1,
  },
  {
    key: "marvel-s-spider-man-play-booster-display-marvel-s-spider-man-spm",
    name: "Marvel's Spider-Man - Play Booster Display - Marvel's Spider-Man (SPM)",
    description: "Marvel's Spider-Man Play Booster Display brings the full Spider-Verse to your draft table. This display contains 30 Play Boosters, each with 14 Magic cards, a guaranteed rare or better, and at least one traditional foil—delivering 420 total cards across one of Universes Beyond's most anticipated crossover sets.\n\nThe card pool spans four decades of Spider-Man history: Peter Parker in his classic red-and-blue suit, Miles Morales bringing Brooklyn energy to the battlefield, Ghost-Spider and Silk representing the wider Spider-Verse cast, and iconic villains including Green Goblin, Doctor Octopus, Venom, and the Sinister Six as legendary creatures and powerful spells. Web counter mechanics reward building sticky, synergistic boards, while the team-up theme mirrors the cooperative spirit of the comics.\n\nPlay Boosters are the primary format product for draft and sealed events, with pack contents that scale from useful commons to mythic chase cards. Borderless comic-art showcase treatments appear at all rarities, and traditional foils show up in each pack. The set is legal in Standard and Commander formats, with the legendary roster feeding directly into Spider-themed Commander decks.\n\nWhether you're running a Spider-Man draft event, cracking packs for your collection, or building the ultimate Marvel Commander deck, this Play Booster Display offers excellent depth and replayability. Factory sealed, sourced from authorized Wizards of the Coast distributors. Ships within the United States via USPS.",
    category: "magic",
    price: 12107,
    image: "https://files.stripe.com/links/MDB8YWNjdF8xU2JEWWRSM1djdWNhUXFwfGZsX2xpdmVfbUhzSmdqdDBsTmRBdVFsb0NrY0tZcXJP00IlgOz1BL",
    sortOrder: 999,
    active: true,
    quantity: 1,
  },
  {
    key: "secrets-of-strixhaven-play-booster-display-secrets-of-strixhaven-sos",
    name: "Secrets of Strixhaven - Play Booster Display - Secrets of Strixhaven (SOS)",
    description: "Secrets of Strixhaven Play Booster Display returns to Magic's most prestigious mage school for a deeper look at the mysteries buried beneath its hallowed halls. This display contains 30 Play Boosters, each with 14 Magic cards, a guaranteed rare or better, and at least one traditional foil—420 cards of second-year curricula from Strixhaven's five elite magical colleges.\n\nSilverquill, Prismari, Witherbloom, Lorehold, and Quandrix are back with expanded card pools that build on established archetypes while unlocking more complex and dangerous spells. Each college brings its own two-color identity: Silverquill's black-white rhetoric and manipulation, Prismari's blue-red elemental artistry, Witherbloom's black-green life-and-death exchange, Lorehold's red-white historical magic, and Quandrix's blue-green mathematical scaling.\n\nThe set escalates the stakes from the original Strixhaven, with deeper mysteries surfacing across the campus, rival faction politics intensifying, and legendary professors taking center stage in ways the original set only hinted at. Showcase treatments draw from the original Strixhaven's academic aesthetics—expect mystical archive-style reprints, professor-frame legendary creatures, and campus-art basic lands.\n\nSecrets of Strixhaven is an excellent draft environment for fans of multicolor synergy and the original Strixhaven experience. Commander players building college-themed or spellslinger decks will find strong additions across all five guilds.\n\nFactory sealed, sourced from authorized Wizards of the Coast distributors. Ships within the United States via USPS.",
    category: "magic",
    price: 13002,
    image: "https://files.stripe.com/links/MDB8YWNjdF8xU2JEWWRSM1djdWNhUXFwfGZsX2xpdmVfdFk4b05jTFBIU1o0ZGtuRFc1RkRycGVa00lWautCp1",
    sortOrder: 999,
    active: true,
    quantity: 2,
  },
  {
    key: "tarkir-dragonstorm-play-booster-display-tarkir-dragonstorm-tdm",
    name: "Tarkir: Dragonstorm - Play Booster Display - Tarkir: Dragonstorm (TDM)",
    description: "Tarkir: Dragonstorm Play Booster Display returns to Magic's most dragon-obsessed plane for an epic clash between five clans and the Spirit Dragons they serve. This display contains 30 Play Boosters, each with 14 Magic: The Gathering cards, a guaranteed rare or better, at least one traditional foil, and a 20% chance of a bonus foil basic land.\n\nThe set's defining feature is its five-clan structure, each built around a distinct three-color combination. One clan favors aggressive dragon-riding combat, another leverages cunning and control, a third leans into resilience and endurance—each with its own mechanical identity and legendary Spirit Dragon as its anchor commander. Powerful dragonstorms spiral across the plane, creating escalating-threat mechanics that reward both aggression and long-game strategies.\n\nChase targets include Borderless dragon showcase treatments, alternate-art Spirit Dragon legendaries in traditional foil, serialized Dragon Lord cards for premium collectors, and the full cycle of clan-specific mythic rares. The set is Standard and Commander legal, and the five Spirit Dragon legendaries have generated strong Commander demand since release.\n\nWith accessible pack pricing, a strong draft environment centered around three-color clan synergies, and a legendary-dense card pool for Commander players, Tarkir: Dragonstorm is a well-rounded box for any Magic player.\n\nFactory sealed, sourced from authorized Wizards of the Coast distributors. Ships within the United States via USPS.",
    category: "magic",
    price: 13017,
    image: "https://files.stripe.com/links/MDB8YWNjdF8xU2JEWWRSM1djdWNhUXFwfGZsX2xpdmVfdlYzeFFQYldJNDRxWVpwdm01QmJuYWdq00ZRVVZQMI",
    sortOrder: 999,
    active: true,
    quantity: 2,
  },
  {
    key: "teenage-mutant-ninja-turtles-play-booster-display-teenage-mutant-ninja-turtles-tmt",
    name: "Teenage Mutant Ninja Turtles - Play Booster Display - Teenage Mutant Ninja Turtles (TMT)",
    description: "Teenage Mutant Ninja Turtles Play Booster Display drops the heroes in a half-shell onto the Magic battlefield in one of Universes Beyond's most high-energy crossovers. This display contains 30 Play Boosters, each with 14 Magic cards and a guaranteed rare or better—bringing Leonardo, Michelangelo, Donatello, and Raphael to your draft table.\n\nThe set's mechanical centrepiece is the Sneak mechanic, which rewards ambush-style play that channels the Turtles' guerrilla tactics in the sewers of New York City. Mutagen tokens power up your creatures over time, mirroring the ooze-infused strength that defines the TMNT universe. Both mechanics build toward explosive, board-flooding finishers that Commander players and Limited drafters will love.\n\nThe card pool spans four decades of TMNT lore: the original Mirage Comics era, the classic 1987 cartoon, the 2003 animated series, and modern comics. Iconic characters—Shredder, Bebop, Rocksteady, Casey Jones, April O'Neil, and Splinter—appear as legendary creatures, removal spells, and supporting cards. Borderless comic-panel showcase treatments bring the bold art of the original Mirage comics to life.\n\nGreat for casual TMNT fans cracking their first sealed product and experienced players hunting ninja-clan Commander pieces alike. Factory sealed, sourced from authorized Wizards of the Coast distributors. Ships within the United States via USPS.",
    category: "magic",
    price: 13946,
    image: "https://files.stripe.com/links/MDB8YWNjdF8xU2JEWWRSM1djdWNhUXFwfGZsX2xpdmVfTFhFUmtnQjI2QTBVN0N1MVN3S3VQRWY300SPJS5HYi",
    sortOrder: 999,
    active: true,
    quantity: 6,
  },
  {
    key: "wilds-of-eldraine-collector-booster-display-wilds-of-eldraine-woe",
    name: "Wilds of Eldraine - Collector Booster Display - Wilds of Eldraine (WOE)",
    description: "Wilds of Eldraine Collector Booster Display is the premium way to explore Magic's fairytale plane at its most spectacular. This display contains 12 Collector Boosters, densely packed with the set's rarest and most visually striking treatments—every pack guaranteed to contain multiple premium foil cards and at least five rares or mythic rares.\n\nEldraine is a plane steeped in dark fairy tale lore: cursed sleeping kingdoms, enchanted forests, and warring courts of Faeries and Humans. Wilds of Eldraine ventures beyond the royal courts into the enchanted wilderness, where ancient magic runs wild and story-cursed Roles reshape creatures on the battlefield. Collector Boosters are home to the Storybook showcase treatments—cards illustrated in the style of illuminated manuscript pages, with art direction unlike anything else in Magic.\n\nChase targets include foil and non-foil Storybook showcase mythics, Enchanting Tale special guest reprints featuring eternal and Commander staples in fresh Eldraine-themed art, and alternate-art legendary Faeries for tribal Commander builds. The Enchanting Tale reprint sheet drives significant collector value, with widely played Commander staples appearing in full thematic art for the first time.\n\nWilds of Eldraine Collector Boosters offer both the immediate excitement of opening premium product and long-term collection value through a strong reprint sheet. Factory sealed, sourced from authorized Wizards of the Coast distributors. Ships within the United States via USPS.",
    category: "magic",
    price: 113316,
    image: "https://files.stripe.com/links/MDB8YWNjdF8xU2JEWWRSM1djdWNhUXFwfGZsX2xpdmVfbFJxdHAyNmJpTnZSeU1MSUx5dlpHcDE5008Sc7iDAu",
    sortOrder: 999,
    active: true,
    quantity: 1,
  },
];
