// This file is kept for backwards compatibility.
// The canonical sitemap index is at /sitemap-index.xml (generated by @astrojs/sitemap).
// Redirect to the index so any old bookmarks or links still work.
//
// Must not be prerendered: a prerendered route can't emit a real HTTP
// redirect, so Astro would bake this into a static 200 HTML page instead.
export const prerender = false;

export async function GET() {
	return new Response(null, {
		status: 301,
		headers: {
			Location: '/sitemap-index.xml',
		},
	});
}
