// This file is kept for backwards compatibility.
// The canonical sitemap index is at /sitemap-index.xml (generated by @astrojs/sitemap).
// Redirect to the index so any old bookmarks or links still work.
export async function GET() {
	return new Response(null, {
		status: 301,
		headers: {
			Location: '/sitemap-index.xml',
		},
	});
}
